name: New issue for Bottle Request
about: "Submit a request for a bottle"
labels: bottle
title: "FORMULA: Request for a bottle"
body:
  - type: markdown
    attributes:
      value: |
        Please replace FORMULA in the title with the name of the formula you want to be bottled.
        
        Please note we will close your issue without comment if you do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.
  - type: checkboxes
    attributes:
      label: "Please verify that you've done all of the following:"
      options:
        - label: checked that there aren't other open issues for the same formula bottle request
          required: true
        - label: verified that the formula does not have a `bottle` block
          required: true
        - label: ran `brew install FORMULA` successfully
          required: true
